spring:
  ## 数据源相关
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/user?useSSL=false&characterEncoding=utf8 
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  
  ## 认证相关    
  auth:
    impl: local
    loginPage: /login.html
    loginProcessingUrl: /login
    permitUrls: [ /login.html , /login ]

## mybatis配置      
mybatis:
  mapperLocations: classpath:mappers/*.xml
     
jwt:
  secret: secret
  expiration: 7200000
  token: Authorization