#extPropertiesFile: null
projectName: test-service
thirdPartyJarPath: /Users/lixin/FwRepository/framework/code-generator-parent/code-generator/src/test/resources/lib
driver:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/order_db
  username: root
  password: 123456
projectConfig:
#  controllerProject: "src/main/java"
  controllerPackage: "help.lixin.xxx.controller"
#  serviceProject: "src/main/java"
  servicePackage: "help.lixin.xxx.service"
#  modelProject: "src/main/java"
  modelPackage: "help.lixin.xxx.model"
#  mapperProject: "src/main/java"
  mapperPackage: "help.lixin.xxx.mapper"
#  mapperXmlProject: "src/main/resources"
  mapperXmlPackage: "mappers"
tables:
  - tableName: t_order_1
    entityName: Order
    mapperName: OrderMapper

  - tableName: t_order_2
    entityName: Order2
    mapperName: Order2Mapper